Bash: Main only Count from find instead of iterating loop from file
Version1-M-and-G/elk-poc pull request #3
Opened 2017-08-31 09:43 UTC by DavidT12

Check if branch exists
Delete old startelk.sh script
Handle no arguments passed to GitUpdateScript.sh

2017-08-31 09:50 UTC, DavidT12 commented on GitUpdateScript.sh
> +function CheckoutPull(){
new function added to keep code clean

2017-08-31 09:53 UTC, DavidT12 commented on GitUpdateScript.sh
> +branch_name=$1
Reads in perameter when script is called

2017-08-31 09:55 UTC, DavidT12 commented on startelk.sh
> -#: Date        : 24/08/2017
this section is out of date

2017-08-31 09:56 UTC, DavidT12 commented on GitUpdateScript.sh
>  function MoveToCorrectBranch(){
all new logic for this function

2017-08-31 16:16 UTC, bazzani requested changes

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +default_branches=(master develop)
please rename with camelCase format defaultBranches

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +branch_name=$1
we could use a more meaningful name
- requestedBranch

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
>  {
can you please bring all opening curly brackets on to the same line as function name

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +	MoveToCorrectBranch
please indent to match the other statements in the for loop

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +        echo "Branch matched will move to the branch:  "
can you please reword to
Required branch found: $branchName

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +    if [[ ${doesBranchExist} -le 0 ]]
can you please flip the if statement e.g. doesBranchExist > 0
The +ve path is less code, and easier to to read

Alternatively, you could assign a Boolean (true|false) value to the variable, rather than a number, to make it even easier to read

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +function CheckoutPull(){
can you rename to CheckoutBranchAndPull?

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +#: Date        : 31/08/2017
can you please remove this as is changes too often, and we can use the git log to determine when the file last changed.
If you can remind me, I will show you how you can do that easily from IntelliJ IDEA

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
>  #: Title       : UpdateGitRepos.sh
DRY - https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +function FindsWhatBranchRepositoryIsOn() {  #not used anymore can delete
Please delete this unused method

2017-08-31 16:16 UTC, bazzani commented on GitUpdateScript.sh
> +function BranchChecking(){  #not used anymore can delete
Please delete this unused method

2017-09-01 15:49 UTC, DavidT12 commented on GitUpdateScript.sh
> +#: Title       : UpdateGitRepos
Date removed

2017-09-01 15:49 UTC, DavidT12 commented on GitUpdateScript.sh
> +function MoveToDefaultBranches(){
functions have been reordered

2017-09-01 15:51 UTC, DavidT12 commented on GitUpdateScript.sh
> +arrayGitDir=($(find -name .git))
FindGitReposotories() function merged into main

2017-09-01 15:54 UTC, DavidT12 commented on GitUpdateScript.sh
> +    gitDir=${arrayGitDir[$n]}
positional parameters and returns are now being used so the code looks very different to the master branch, but it's really not that different.

2017-09-04 09:24 UTC, bazzani requested changes

2017-09-04 09:24 UTC, bazzani commented on GitUpdateScript.sh
> +        local branchExist=0
can you make the variable function scoped e.g. local branchExist at the top of the function

2017-09-04 09:24 UTC, bazzani commented on GitUpdateScript.sh
> +    for (( x=0; x<${#arrayDefaultBranches[*]}; x++ ))
can you use i for the iterator name

2017-09-04 15:45 UTC, bazzani requested changes

2017-09-04 15:45 UTC, bazzani commented on GitUpdateScript.sh
> +for (( j=0; j<$numberOfGitRepos; j++ ))
can you use i here, j,k comes with nested for loops

2017-09-04 16:33 UTC, bazzani approved these changes

2017-09-04 16:34 UTC, merged