Feature/startstopscripts
Version1-M-and-G/elk-poc pull request #4
Opened 2017-08-31 11:15 UTC by alanc94

2017-08-31 13:03 UTC, bazzani commented
All the scripts are in one directory @alanc94, could you come up with a directory strategy to split them up?

2017-08-31 15:30 UTC, alanc94 commented
"breaking scripts into directories" is the files uploaded in the same layout as in my directories

2017-09-08 15:41 UTC, balajisridhar requested changes

2017-09-08 15:41 UTC, balajisridhar commented on bin/elasticsearch.sh
> +ELK_POC_HOME=~/ELK_POC_HOME/
Can you add comments to all of the script files like below? 
#!/bin/bash
#: Title       : Update Git Repositories
#: Author      : 
#: Version     : 1.0
#: Description : 
#: Options     : None

2017-09-08 15:41 UTC, balajisridhar commented on bin/elasticsearch.sh
> +echo "elasticsearch is running"
Do you assert successful start up, before echoing? This might be misleading to users in few occasion.

2017-09-08 15:41 UTC, balajisridhar commented on bin/elasticsearch.sh
> +echo "elasticsearch has shut down"
Same here, how do we know if the process is shut down or still running? Need to change this across scripts.

2017-09-08 15:41 UTC, balajisridhar commented on bin/elasticsearchFiles/startES.sh
> +sudo sysctl -w vm.max_map_count=262144
Can you add a comment on why we need to set this value? Would be helpful for new comers.

2017-09-08 15:41 UTC, balajisridhar commented on bin/elasticsearchFiles/startES.sh
> +# sh $ELK_HOME/elasticsearch-5.5.0/bin/elasticsearch -d > $LOG_DIR/$logname
I think we need to remove the commented commands, might be misleading sometimes.

2017-09-08 16:22 UTC, balajisridhar commented on bin/elasticsearchFiles/startES.sh
> +logs=~/ELK_POC_HOME/logs
Please replace all the ~/ELK_POC_HOME with env variable $ELK_POC_HOME 
e.g logs= $ELK_POC_HOME/logs.

Add a comment in the readme/document, that it is expected to set these ENV variables by the user.

2017-09-11 10:48 UTC, alanc94 commented
Up to date scripts have been added

2017-09-13 16:32 UTC, alanc94 commented
Scripts are up to date and ready for the demo

2017-09-15 14:13 UTC, balajisridhar commented on bin/elasticsearchScripts/stopES.sh
> +		#echo "Number of process:" $proc_count
Remove this line, if not required.

2017-09-15 14:16 UTC, balajisridhar commented on bin/kibanaScripts/startKB.sh
> +#starting kibana
Remove the comments, if its not relevant anymore

2017-09-15 14:16 UTC, balajisridhar commented on bin/kibanaScripts/startKB.sh
> +#to use JAVA_8_HOME as JDK8 is the minimum requisite
Remove the comments, if its not relevant anymore

2017-09-15 14:16 UTC, balajisridhar commented on bin/logstashScripts/startLS.sh
> +#starting logstash
Remove the comments, if its not relevant anymore

2017-09-15 14:59 UTC, bazzani requested changes

2017-09-15 14:59 UTC, bazzani commented on bin/elasticsearchScripts/startES.sh
> +#to use JAVA_8_HOME as JDK8 is the minimum requisite
should these commented out lines be removed?

2017-09-15 14:59 UTC, bazzani commented on bin/kibanaScripts/stopKB.sh
> +		#echo "Number of process:" $proc_count
should these commented out lines be removed?

2017-09-15 14:59 UTC, bazzani commented on bin/logstashScripts/logstash.conf
> +path => "/home/alan/gitfolder/jersey/**/*.java"
could you specify a more generic location, rather than your home
  - e.g. {ELK_SRC_HOME}

so that its clear to change the value

2017-09-15 15:36 UTC, alanc94 commented
PR changes have been made

2017-09-15 16:08 UTC, balajisridhar approved these changes

2017-09-15 16:33 UTC, bazzani requested changes

2017-09-15 16:33 UTC, bazzani commented on bin/logstashScripts/logstash.conf
> +       start_position => "beginning"
indent all elements please

2017-09-15 16:43 UTC, bazzani commented on bin/logstashScripts/logstash.conf
> +       start_position => "beginning"
All done

2017-09-15 16:44 UTC, bazzani approved these changes

2017-09-15 16:52 UTC, merged